export type BioLevel = 'básico' | 'intermedio' | 'avanzado';

export interface BiologyNode {
  id:          string;
  label:       string;
  shortLabel:  string;
  desc:        string;
  icon:        string;
  color:       string;
  level:       BioLevel;
  prompt:      string;
  optional?:   boolean;
  branch:      'main' | 'structure' | 'energy' | 'genetics' | 'applied';
  x:           number;
  y:           number;
}

export interface BiologyEdge {
  from: string;
  to:   string;
}

const C_BASIC = '#ff6b35';
const C_INTER = '#ffaa00';
const C_ADV   = '#ff3060';
const C_OPT   = '#a855f7';

export const BIOLOGY_NODES: BiologyNode[] = [
  // ── Main trunk (y=4) ──────────────────────────────────────
  {
    id: 'fundamentos-quimicos',
    label: 'Fundamentos Químicos de la Vida',
    shortLabel: 'Fundamentos Químicos',
    desc: 'Agua, pH, enlaces químicos y elementos esenciales. La base química sobre la que se construye toda la biología celular.',
    icon: '⚛',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame los fundamentos químicos de la vida: propiedades del agua, pH, enlaces químicos (covalente, iónico, puente de hidrógeno) y los elementos esenciales para la vida, con ejemplos biológicos.',
    branch: 'main',
    x: 0, y: 4,
  },
  {
    id: 'bioquimica-macromoleculas',
    label: 'Bioquímica de Macromoléculas',
    shortLabel: 'Macromoléculas',
    desc: 'Las cuatro macromoléculas biológicas: carbohidratos, lípidos, proteínas y ácidos nucleicos. Estructura, función y relaciones.',
    icon: '🧬',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame la bioquímica de las macromoléculas: carbohidratos, lípidos, proteínas y ácidos nucleicos, su estructura, funciones y relaciones entre ellas.',
    branch: 'main',
    x: 1, y: 4,
  },
  {
    id: 'teoria-celular',
    label: 'Teoría Celular y Tipos de Células',
    shortLabel: 'Teoría Celular',
    desc: 'Historia y postulados de la teoría celular. Diferencias fundamentales entre procariotas y eucariotas. El célula como unidad de vida.',
    icon: '🔬',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame la teoría celular: sus postulados, historia, y las diferencias entre células procariotas y eucariotas, con ejemplos de cada tipo.',
    branch: 'main',
    x: 2, y: 4,
  },
  {
    id: 'membrana-plasmatica',
    label: 'Estructura de la Membrana Plasmática',
    shortLabel: 'Membrana',
    desc: 'Modelo del mosaico fluido: fosfolípidos, colesterol, proteínas integrales y periféricas. Función de barrera selectiva y comunicación.',
    icon: '🛡',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame la estructura de la membrana plasmática: modelo del mosaico fluido, fosfolípidos, colesterol, proteínas integrales y periféricas, y sus funciones.',
    branch: 'main',
    x: 3, y: 4,
  },
  {
    id: 'transporte-celular',
    label: 'Transporte Celular',
    shortLabel: 'Transporte',
    desc: 'Mecanismos de intercambio a través de la membrana: pasivo (sin energía) y activo (con ATP). Equilibrio osmótico y captación de nutrientes.',
    icon: '🔄',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame el transporte celular a través de la membrana: transporte pasivo y activo, con ejemplos concretos de cada mecanismo.',
    branch: 'main',
    x: 4, y: 4,
  },
  {
    id: 'organelos-celulares',
    label: 'Organelos Celulares',
    shortLabel: 'Organelos',
    desc: 'Los organelos de la célula eucariota: núcleo, retículo endoplásmico, Golgi, mitocondrias, lisosomas, peroxisomas y citoesqueleto.',
    icon: '🏭',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame los organelos celulares de la célula eucariota: núcleo, retículo endoplásmico, aparato de Golgi, mitocondrias, lisosomas, peroxisomas y citoesqueleto, con sus funciones.',
    branch: 'main',
    x: 5, y: 4,
  },
  {
    id: 'metabolismo-energetico',
    label: 'Metabolismo Energético',
    shortLabel: 'Metabolismo',
    desc: 'Cómo las células obtienen energía: glucólisis, respiración celular y fotosíntesis. ATP como moneda energética universal.',
    icon: '🔋',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame el metabolismo energético celular: glucólisis, respiración celular (ciclo de Krebs y cadena de transporte de electrones) y fotosíntesis, con el ATP como moneda energética.',
    branch: 'main',
    x: 6, y: 4,
  },
  {
    id: 'ciclo-celular',
    label: 'Ciclo Celular y División',
    shortLabel: 'Ciclo Celular',
    desc: 'Interfase y división celular. Regulación por ciclinas y CDKs. Mitosis para crecimiento y meiosis para reproducción sexual.',
    icon: '⊘',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame el ciclo celular y la división: interfase (G1, S, G2), mitosis y meiosis, con la regulación por ciclinas y CDKs.',
    branch: 'main',
    x: 7, y: 4,
  },
  {
    id: 'comunicacion-celular',
    label: 'Comunicación Celular / Señalización',
    shortLabel: 'Señalización',
    desc: 'Cómo las células se comunican: receptores, mensajeros y vías de transducción. Respuesta hormonal y neurotransmisión.',
    icon: '📡',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la comunicación y señalización celular: tipos de receptores, mensajeros secundarios y vías de transducción de señales, con ejemplos de respuesta hormonal.',
    branch: 'main',
    x: 8, y: 4,
  },
  {
    id: 'genetica-molecular',
    label: 'Genética Molecular',
    shortLabel: 'Genética Mol.',
    desc: 'El dogma central de la biología molecular: replicación, transcripción y traducción. Cómo la información genética se convierte en proteínas.',
    icon: '🧬',
    color: C_ADV,
    level: 'avanzado',
    prompt: 'Explícame la genética molecular y el dogma central: replicación del DNA, transcripción a RNA y traducción a proteínas, con las enzimas involucradas en cada proceso.',
    branch: 'main',
    x: 9, y: 4,
  },
  {
    id: 'regulacion-genica',
    label: 'Regulación Génica',
    shortLabel: 'Reg. Génica',
    desc: 'Control de la expresión génica: epigenética, factores de transcripción, RNA no codificante. Cómo se encienden y apagan los genes.',
    icon: '🎚',
    color: C_ADV,
    level: 'avanzado',
    prompt: 'Explícame la regulación génica: mecanismos epigenéticos (metilación, histonas), factores de transcripción, RNA no codificante (miRNA, lncRNA) y cómo se controla la expresión.',
    branch: 'main',
    x: 10, y: 4,
  },
  {
    id: 'apoptosis',
    label: 'Apoptosis y Muerte Celular Programada',
    shortLabel: 'Apoptosis',
    desc: 'Mecanismo de suicidio celular: caspasas, vía extrínseca e intrínseca. Importancia en desarrollo, homeostasis y prevención del cáncer.',
    icon: '☠',
    color: C_OPT,
    level: 'avanzado',
    optional: true,
    prompt: 'Explícame la apoptosis (muerte celular programada): caspasas, vía extrínseca (receptores de muerte) e intrínseca (mitocondrial), y su importancia en desarrollo y prevención del cáncer.',
    branch: 'applied',
    x: 11, y: 3,
  },
  {
    id: 'cancer',
    label: 'Cáncer y Ciclo Celular Descontrolado',
    shortLabel: 'Cáncer',
    desc: 'Oncogenes, genes supresores de tumores, puntos de control fallidos. La biología molecular del cáncer como enfermedad celular.',
    icon: '⚠',
    color: C_OPT,
    level: 'avanzado',
    optional: true,
    prompt: 'Explícame el cáncer desde la biología celular: oncogenes, genes supresores de tumores (p53, Rb), fallas en puntos de control, metástasis y terapias dirigidas.',
    branch: 'applied',
    x: 11, y: 5,
  },

  // ── Structure branch (above main, y=0-3) ──────────────────
  {
    id: 'carbohidratos-lipidos',
    label: 'Carbohidratos y Lípidos',
    shortLabel: 'Carb. y Lípidos',
    desc: 'Estructura de azúcares simples a polisacáridos. Lípidos: fosfolípidos, esteroides y triacilgliceroles. Funciones energéticas y estructurales.',
    icon: '🍬',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame los carbohidratos y lípidos en detalle: monosacáridos, disacáridos, polisacáridos, fosfolípidos, esteroides y triacilgliceroles, con sus funciones biológicas.',
    branch: 'structure',
    x: 1, y: 2,
  },
  {
    id: 'proteinas',
    label: 'Proteínas y Estructura Proteica',
    shortLabel: 'Proteínas',
    desc: 'Aminoácidos, estructura primaria, secundaria, terciaria y cuaternaria. Plegamiento, desnaturalización y relación estructura-función.',
    icon: '⛓',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame las proteínas y su estructura: aminoácidos, niveles de estructura (primaria, secundaria, terciaria, cuaternaria), plegamiento y desnaturalización.',
    branch: 'structure',
    x: 1, y: 3,
  },
  {
    id: 'acidos-nucleicos',
    label: 'Ácidos Nucleicos (DNA/RNA)',
    shortLabel: 'DNA / RNA',
    desc: 'Nucleótidos, estructura del DNA y RNA, emparejamiento de bases, replicación semiconservativa y diferencias entre DNA y RNA.',
    icon: '🧪',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame los ácidos nucleicos: estructura de nucleótidos, DNA y RNA, emparejamiento de bases, replicación semiconservativa y diferencias clave entre DNA y RNA.',
    branch: 'structure',
    x: 1, y: 5,
  },
  {
    id: 'procariotas',
    label: 'Células Procariotas',
    shortLabel: 'Procariotas',
    desc: 'Estructura de bacterias y arqueas: nucleoide, pared celular, flagelos, plásmidos. Organismos más abundantes del planeta.',
    icon: '🦠',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame las células procariotas en detalle: estructura del nucleoide, pared celular, flagelos, plásmidos, y diferencias entre bacterias y arqueas.',
    branch: 'structure',
    x: 2, y: 3,
  },
  {
    id: 'eucariotas',
    label: 'Células Eucariotas',
    shortLabel: 'Eucariotas',
    desc: 'Células animal vs vegetal. Núcleo definido, organelos membrana-doblados. Complejidad y especialización celular.',
    icon: '🦠',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame las células eucariotas: núcleo definido, organelos membrana-doblados, y las diferencias entre células animales y vegetales.',
    branch: 'structure',
    x: 2, y: 5,
  },
  {
    id: 'transporte-pasivo',
    label: 'Transporte Pasivo',
    shortLabel: 'T. Pasivo',
    desc: 'Difusión simple, difusión facilitada y ósmosis. Movimiento a favor del gradiente de concentración sin gasto de ATP.',
    icon: '→',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame el transporte pasivo: difusión simple, difusión facilitada (canales y transportadores) y ósmosis, con ejemplos y su importancia fisiológica.',
    branch: 'structure',
    x: 4, y: 3,
  },
  {
    id: 'transporte-activo',
    label: 'Transporte Activo',
    shortLabel: 'T. Activo',
    desc: 'Bombas (Na+/K+ ATPasa), cotransporte, endocitosis y exocitosis. Movimiento contra gradiente usando energía celular.',
    icon: '⇄',
    color: C_BASIC,
    level: 'básico',
    prompt: 'Explícame el transporte activo: bomba Na+/K+ ATPasa, cotransporte, endocitosis (fagocitosis, pinocitosis, mediada por receptor) y exocitosis.',
    branch: 'structure',
    x: 4, y: 5,
  },

  // ── Organelos branch (y=0-3 and y=5-7) ────────────────────
  {
    id: 'nucleo',
    label: 'Núcleo y Envoltura Nuclear',
    shortLabel: 'Núcleo',
    desc: 'Envoltura nuclear doble, poros nucleares, nucleoplasma, nucleolo. Almacenamiento y protección del material genético.',
    icon: '◉',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame el núcleo celular: envoltura nuclear doble, poros nucleares, nucleoplasma, nucleolo y su papel en la protección y expresión del material genético.',
    branch: 'structure',
    x: 5, y: 1,
  },
  {
    id: 'reticulo-endoplasmico',
    label: 'Retículo Endoplásmico',
    shortLabel: 'R. Endoplásmico',
    desc: 'RE rugoso con ribosomas: síntesis de proteínas. RE liso: síntesis de lípidos, detoxificación y almacenamiento de calcio.',
    icon: '〰',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame el retículo endoplásmico: diferencias entre RE rugoso (síntesis de proteínas) y RE liso (síntesis de lípidos, detoxificación, calcio), con su relación con otros organelos.',
    branch: 'structure',
    x: 5, y: 2,
  },
  {
    id: 'aparato-golgi',
    label: 'Aparato de Golgi',
    shortLabel: 'Golgi',
    desc: 'Cisternas, modificaciones postraduccionales, glicosilación, clasificación y empaquetado de proteínas para secreción.',
    icon: '📦',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame el aparato de Golgi: estructura de cisternas, modificaciones postraduccionales, glicosilación, clasificación y secreción de proteínas.',
    branch: 'structure',
    x: 5, y: 3,
  },
  {
    id: 'mitocondrias',
    label: 'Mitocondrias',
    shortLabel: 'Mitocondrias',
    desc: 'Doble membrana, crestas, matriz mitocondrial, ATP sintasa. La central energética de la célula y teoría endosimbiótica.',
    icon: '⚡',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame las mitocondrias: doble membrana, crestas, matriz, ATP sintasa, teoría endosimbiótica y su papel como central energética celular.',
    branch: 'structure',
    x: 5, y: 5,
  },
  {
    id: 'lisosomas-peroxisomas',
    label: 'Lisosomas y Peroxisomas',
    shortLabel: 'Lisosomas',
    desc: 'Lisosomas: digestión intracelular con enzimas hidrolíticas. Peroxisomas: oxidación y detoxificación, catalasa.',
    icon: '💧',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame los lisosomas y peroxisomas: enzimas hidrolíticas, digestión intracelular, oxidación, detoxificación y la enzima catalasa.',
    branch: 'structure',
    x: 5, y: 6,
  },
  {
    id: 'citoesqueleto',
    label: 'Citoesqueleto',
    shortLabel: 'Citoesqueleto',
    desc: 'Microtúbulos, microfilamentos y filamentos intermedios. Estructura, movimiento, división celular y transporte intracelular.',
    icon: '🕸',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame el citoesqueleto: microtúbulos (tubulina), microfilamentos (actina) y filamentos intermedios, sus funciones estructurales y de transporte intracelular.',
    branch: 'structure',
    x: 5, y: 7,
  },

  // ── Energy branch (y=3 and y=5) ───────────────────────────
  {
    id: 'glucolisis',
    label: 'Glucólisis',
    shortLabel: 'Glucólisis',
    desc: 'Degradación de glucosa a piruvato en el citoplasma. 10 enzimas, 2 ATP netos y 2 NADH. Primera etapa de prácticamente todo el metabolismo.',
    icon: '🍬',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la glucólisis paso a paso: las 10 reacciones enzimáticas, rendimiento de ATP y NADH, y su regulación, desde glucosa hasta piruvato.',
    branch: 'energy',
    x: 6, y: 3,
  },
  {
    id: 'respiracion-celular',
    label: 'Respiración Celular',
    shortLabel: 'Respiración',
    desc: 'Ciclo de Krebs en la matriz mitocondrial y cadena de transporte de electrones en la membrana interna. ~30-32 ATP por glucosa.',
    icon: '💨',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la respiración celular: ciclo de Krebs (reacciones, rendimiento de NADH/FADH2/ATP) y la cadena de transporte de electrones (complejos I-IV, ATP sintasa, quimiosmosis).',
    branch: 'energy',
    x: 6, y: 5,
  },
  {
    id: 'fotosintesis',
    label: 'Fotosíntesis',
    shortLabel: 'Fotosíntesis',
    desc: 'Reacciones lumínicas en tilacoides y ciclo de Calvin en el estroma. Conversión de energía solar en energía química.',
    icon: '☀',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la fotosíntesis: reacciones lumínicas (fotosistemas I y II, cadena de electrones, ATP y NADPH) y el ciclo de Calvin (fijación de CO2, RuBisCO).',
    branch: 'energy',
    x: 6, y: 6,
  },

  // ── Cell cycle branch (y=3 and y=5) ───────────────────────
  {
    id: 'interfase',
    label: 'Interfase (G1, S, G2)',
    shortLabel: 'Interfase',
    desc: 'Crecimiento (G1), replicación del DNA (S), preparación para división (G2). Puntos de control y regulación.',
    icon: '◐',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la interfase del ciclo celular: fase G1 (crecimiento), fase S (replicación del DNA), fase G2 (preparación), y los puntos de control que regulan cada transición.',
    branch: 'energy',
    x: 7, y: 3,
  },
  {
    id: 'mitosis',
    label: 'Mitosis',
    shortLabel: 'Mitosis',
    desc: 'Profase, metafase, anafase y telofase. División ecuacional: dos células hijas genéticamente idénticas.',
    icon: '⊙',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la mitosis en detalle: profase, metafase, anafase y telofase, con los eventos clave de cada fase y la citocinesis.',
    branch: 'energy',
    x: 7, y: 5,
  },
  {
    id: 'meiosis',
    label: 'Meiosis',
    shortLabel: 'Meiosis',
    desc: 'Dos divisiones nucleares con una replicación. Recombinación genética, variabilidad y producción de gametos haploides.',
    icon: '◑',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame la meiosis: meiosis I (reduccional, entrecruzamiento) y meiosis II (ecuacional), con la importancia de la variabilidad genética y la producción de gametos.',
    branch: 'energy',
    x: 7, y: 6,
  },

  // ── Signaling branch (y=3 and y=5) ────────────────────────
  {
    id: 'receptores-membrana',
    label: 'Receptores de Membrana',
    shortLabel: 'Receptores',
    desc: 'Receptores acoplados a proteína G, receptores tirosina quinasa, canales iónicos. Reconocimiento de señales extracelulares.',
    icon: '🔌',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame los receptores de membrana: acoplados a proteína G (GPCR), tirosina quinasa (RTK) y canales iónicos, con sus mecanismos de activación.',
    branch: 'energy',
    x: 8, y: 3,
  },
  {
    id: 'vias-transduccion',
    label: 'Vías de Transducción de Señales',
    shortLabel: 'Transducción',
    desc: 'Cascadas de amplificación: AMPc, DAG/IP3, MAPK. Cómo una señal extracelular se convierte en respuesta celular.',
    icon: '🔀',
    color: C_INTER,
    level: 'intermedio',
    prompt: 'Explícame las vías de transducción de señales: cascadas de AMPc, fosfolipasa C (DAG/IP3), vía MAPK, y cómo se amplifica y regula la señal.',
    branch: 'energy',
    x: 8, y: 5,
  },

  // ── Genetics branch (y=3 and y=5) ─────────────────────────
  {
    id: 'replicacion-dna',
    label: 'Replicación del DNA',
    shortLabel: 'Replicación',
    desc: 'DNA polimerasa, horquilla de replicación, hebras líder y rezagada, fragmentos de Okazaki. Fidelidad y corrección de errores.',
    icon: '⧉',
    color: C_ADV,
    level: 'avanzado',
    prompt: 'Explícame la replicación del DNA: origenes de replicación, DNA polimerasa, hebras líder y rezagada, fragmentos de Okazaki, primasa, ligasa y mecanismos de corrección.',
    branch: 'genetics',
    x: 9, y: 3,
  },
  {
    id: 'transcripcion',
    label: 'Transcripción',
    shortLabel: 'Transcripción',
    desc: 'RNA polimerasa, promotores, factores de transcripción, procesamiento del RNA (splicing, cap, poli-A). Del DNA al mRNA.',
    icon: '✎',
    color: C_ADV,
    level: 'avanzado',
    prompt: 'Explícame la transcripción: RNA polimerasa, promotores, factores de transcripción, y el procesamiento del RNA mensajero (splicing, cap 5\', cola poli-A).',
    branch: 'genetics',
    x: 9, y: 5,
  },
  {
    id: 'traduccion',
    label: 'Traducción (Síntesis de Proteínas)',
    shortLabel: 'Traducción',
    desc: 'Ribosomas, tRNA, código genético, iniciación, elongación y terminación. Del mRNA a la proteína funcional.',
    icon: '🏗',
    color: C_ADV,
    level: 'avanzado',
    prompt: 'Explícame la traducción (síntesis de proteínas): ribosomas, tRNA, código genético, iniciación, elongación, terminación y modificaciones postraduccionales.',
    branch: 'genetics',
    x: 9, y: 6,
  },
];

export const BIOLOGY_EDGES: BiologyEdge[] = [
  // Main trunk
  { from: 'fundamentos-quimicos',    to: 'bioquimica-macromoleculas' },
  { from: 'bioquimica-macromoleculas', to: 'teoria-celular' },
  { from: 'teoria-celular',          to: 'membrana-plasmatica' },
  { from: 'membrana-plasmatica',     to: 'transporte-celular' },
  { from: 'transporte-celular',      to: 'organelos-celulares' },
  { from: 'organelos-celulares',     to: 'metabolismo-energetico' },
  { from: 'metabolismo-energetico',  to: 'ciclo-celular' },
  { from: 'ciclo-celular',           to: 'comunicacion-celular' },
  { from: 'comunicacion-celular',    to: 'genetica-molecular' },
  { from: 'genetica-molecular',      to: 'regulacion-genica' },
  { from: 'regulacion-genica',       to: 'apoptosis' },
  { from: 'regulacion-genica',       to: 'cancer' },

  // Macromoléculas children
  { from: 'bioquimica-macromoleculas', to: 'carbohidratos-lipidos' },
  { from: 'bioquimica-macromoleculas', to: 'proteinas' },
  { from: 'bioquimica-macromoleculas', to: 'acidos-nucleicos' },

  // Teoría celular children
  { from: 'teoria-celular',          to: 'procariotas' },
  { from: 'teoria-celular',          to: 'eucariotas' },

  // Transporte children
  { from: 'transporte-celular',      to: 'transporte-pasivo' },
  { from: 'transporte-celular',      to: 'transporte-activo' },

  // Organelos children
  { from: 'organelos-celulares',     to: 'nucleo' },
  { from: 'organelos-celulares',     to: 'reticulo-endoplasmico' },
  { from: 'organelos-celulares',     to: 'aparato-golgi' },
  { from: 'organelos-celulares',     to: 'mitocondrias' },
  { from: 'organelos-celulares',     to: 'lisosomas-peroxisomas' },
  { from: 'organelos-celulares',     to: 'citoesqueleto' },

  // Metabolismo children
  { from: 'metabolismo-energetico',  to: 'glucolisis' },
  { from: 'metabolismo-energetico',  to: 'respiracion-celular' },
  { from: 'metabolismo-energetico',  to: 'fotosintesis' },

  // Ciclo celular children
  { from: 'ciclo-celular',           to: 'interfase' },
  { from: 'ciclo-celular',           to: 'mitosis' },
  { from: 'ciclo-celular',           to: 'meiosis' },

  // Comunicación children
  { from: 'comunicacion-celular',    to: 'receptores-membrana' },
  { from: 'comunicacion-celular',    to: 'vias-transduccion' },

  // Genética molecular children
  { from: 'genetica-molecular',      to: 'replicacion-dna' },
  { from: 'genetica-molecular',      to: 'transcripcion' },
  { from: 'genetica-molecular',      to: 'traduccion' },
];

export const BIO_BRANCH_COLORS: Record<string, string> = {
  main:      '#ff6b35',
  structure: '#ffaa00',
  energy:    '#00e5a0',
  genetics:  '#ff3060',
  applied:   '#a855f7',
};

export const BIO_LEVEL_COLORS: Record<BioLevel, string> = {
  básico:      '#ff6b35',
  intermedio:  '#ffaa00',
  avanzado:    '#ff3060',
};
