export const discoverSections = [
  {
    className: "section-hero",
    align: "",
    title: "DESCUBRE",
    text: "Descubre el futuro de la tecnología inmersiva en El Salvador.",
    glitch: true,
    indicator: true,
  },
  {
    className: "section-about",
    align: "right",
    title: "Nuestra Misión",
    text: "Athernix es un ecosistema tecnológico que integra realidad virtual e inteligencia artificial para transformar la educación, el turismo y el bienestar psicológico en Centroamérica. Nacimos en El Salvador con la visión de democratizar el acceso a experiencias inmersivas de alta calidad.",
  },
  {
    className: "section-vision",
    align: "left",
    title: "Nuestra Visión",
    text: "Ser la plataforma líder de aprendizaje experiencial en Latinoamérica, donde cada estudiante, docente y profesional pueda explorar el conocimiento sin límites físicos, económicos o geográficos. Creemos que aprender no debería estar limitado por cuatro paredes — el conocimiento es un viaje, y Athernix es el vehículo.",
  },
  {
    className: "section-features",
    align: "left",
    title: "Tres Ejes de Impacto",
    textParts: [
      "Nuestra plataforma se estructura en tres módulos principales: ",
      { text: "Historia Viva VR", className: "highlight-orange" },
      " para educación cultural, ",
      { text: "SVirtual Tours", className: "highlight-red" },
      " para turismo digital, y ",
      { text: "MenteLibre VR", className: "highlight-orange" },
      " para salud mental. Juntos forman un ecosistema unificado de transformación digital.",
    ],
  },
  {
    className: "section-values",
    align: "right",
    title: "Valores Fundacionales",
    textParts: [
      "Accesibilidad: el conocimiento de calidad debe llegar a cualquier estudiante, sin importar su ubicación o recursos. ",
      { text: "Innovación responsable", className: "highlight-orange" },
      ": adoptamos IA, XR y tecnologías emergentes con propósito claro — potenciar el aprendizaje humano, nunca reemplazarlo. ",
      { text: "Identidad cultural", className: "highlight-red" },
      ": honramos el patrimonio de El Salvador y Latinoamérica como punto de partida.",
    ],
  },
  {
    className: "section-roadmap",
    align: "left",
    title: "Trayectoria",
    textParts: [
      "2023: Fundación del proyecto en El Salvador. ",
      "2024: Lanzamiento de ",
      { text: "Ather IA", className: "highlight-orange" },
      ", el ajolote robot conversacional. ",
      "2025: Plataforma multi-módulo con Historia Viva, SVirtual Tours y MenteLibre VR. ",
      "2026: Sistema operativo completo con gamificación por roles. ",
      { text: "2027+: Expansión LATAM", className: "highlight-red" },
      " — alianzas con Guatemala, Honduras, Costa Rica y México.",
    ],
  },
  {
    className: "section-stats",
    align: "right",
    title: "Impacto Medible",
    textParts: [
      { text: "4 módulos", className: "highlight-orange" },
      " activos · ",
      { text: "12 idiomas", className: "highlight-red" },
      " soportados · ",
      { text: "8K de resolución VR", className: "highlight-orange" },
      " · -40% en estrés con MenteLibre · 500h de contenido cultural IA.",
    ],
  },
  {
    className: "section-future",
    align: "left",
    title: "El Futuro",
    text: "Laboratorios STEM físicos en escuelas de El Salvador, suite de creación de contenido para docentes, red latinoamericana con contenido localizado, y Athernix Open Source para que desarrolladores de toda la región contribuyan a su evolución.",
  },
  {
    className: "section-footer",
    align: "center",
    title: "Únete al Futuro",
    text: "Construido con Three.js, React y tecnologías de vanguardia.",
  },
];
